### ISSUE TITLE
考不考虑增加个GUI的版本

### ISSUE THREAD

**Issue by ted423** [ChisBread/qbittorrent_skip_patch#2]
WebUI的问题有如下
https://github.com/qbittorrent/qBittorrent/issues/14556
https://github.com/qbittorrent/qBittorrent/issues/15807
https://github.com/qbittorrent/qBittorrent/issues/15818
https://github.com/qbittorrent/qBittorrent/issues/15976

遇上批量改tracker我也会需要开GUI

**Comment by ChisBread** [comment]
暂无此计划，实际上本项目目前没有多平台release的计划，目前只给出了linux下的qbittorrent-nox。
后续会根据项目热度，考虑是否扩大适配范围、提供更多使用方式。
感谢关注。

**Comment by ted423** [comment]
真心想等大佬的QNAP版本，这可能是唯一能拯救我的QNAP的机会了😢
