### ISSUE TITLE
文件不一致时检验会卡住不动

### ISSUE THREAD

**Issue by we11adam** [ChisBread/qbittorrent_skip_patch#3]
添加种子检验到 16.9% 时无法继续：

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/319494/156692860-715409d5-3964-4423-9369-49653ff7c3c1.png">

如果用右键菜单里的 `Force recheck`，则会卡在 0% 没有进度：
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/319494/156693022-36100dfb-6e4a-4c0b-901d-722fd353a3eb.png">

使用的是 Docker 镜像， tag 为 `4.3.9` ， OS 为 PVE 中虚拟的 黑群 6.2.x 。

感谢！

**Comment by ChisBread** [comment]
试试4.2.5版本，4.3.9似乎有一些未知的问题
