### ISSUE TITLE
跪求breed佬编译个arm64v8版docker镜像的qb

### ISSUE THREAD

**Issue by RenMu-V** [ChisBread/qbittorrent_skip_patch#5]
跪求breed佬编译个arm64v8版docker镜像的qb

**Comment by ChisBread** [comment]
好啊

**Comment by ChisBread** [comment]
已经有别的开发者做啦
https://www.ghostchu.com/qbittorrent-nox-static
https://github.com/Ghost-chu/qbittorrent-nox-static/releases/tag/manual-master_RC_1_2-fasthash
