### ISSUE TITLE
为什么每次启动都会强制更改目录拥有者

### ISSUE THREAD

**Issue by ceozero** [ChisBread/qbittorrent_skip_patch#7]
![image](https://user-images.githubusercontent.com/22513657/201628566-7d33c89f-8fd7-4095-8cb2-1c387c9fbc38.png)

每次启动都会改成abc这个用户为下载目录所有者。
挂载的nfs权限是不允许修改目录所有者的，只会给读写权限。

虽然不影响使用，只不过看起来这报错挺头疼的。

**Comment by ChisBread** [comment]
这里我偷了一个懒，直接使用linuxserver/qbittorrent作为基础镜像，也就是说这段逻辑是linuxserver写的

```dockerfile
FROM linuxserver/qbittorrent:latest
COPY qbittorrent-nox /usr/bin/qbittorrent-nox
```

相关repo: https://github.com/linuxserver/docker-qbittorrent
